[tools]
ruby = "latest"
nodejs = "lts"
rust = "1.92.0"
go = "latest"
python = "latest"
zig = "0.15.2"
uv = "latest"
pnpm = "latest"
bun = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
